### ISSUE TITLE
Carrier channels not deleted if bot is restarted while timer running

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#372]
Presently channel delete timer called by `m.done`/`m.complete` runs as a simple `await asyncio.sleep`. Restarting the bot stops this timer and thus prevents automatic channel deletion. Channel deletion should be processed no matter what happens to the bot after `m.complete`/`m.done` is called.

**Comment by cimspin** [comment]
Promoting this to important as it'd make updating a lot less hairy.

To expand on @TuggyBoat's comment, something along the lines of: a new column in the `missions` table in missions.db, `is_complete`, added on first run. When a mission is completed, assign a value to `is_complete`. On startup scan for any rows with `is_complete` value and process them using the regular `_cleanup_completed_mission` function. Worst case is channel delete is delayed by 15 minutes.

**Comment by skiedude** [comment]
I don't see any migration files, have we done those in the past? how have we handled db migrations/updates in the past?

**Comment by cimspin** [comment]
> I don't see any migration files, have we done those in the past? how have we handled db migrations/updates in the past?

Just checked the DB to see if the column existed and if not, add it. Previously this was done as per lines 214-250

**Comment by skiedude** [comment]
We have a chicken before the egg type situation. 
In the function _cleanup_completed_mission we delete the mission from the missions table
 `mission_db.execute(f'''DELETE FROM missions WHERE carrier LIKE (?)''', ('%' + mission_data.carrier_name + '%',))`

We then queue the channel deletion. That means if the bot were restarted during that 15 minute timer, querying the missions table wouldn't result in anything useful because the mission was already deleted. 

Now we could move the mission deletion to take place after the channel deletion, in which case a restart would still find the missions entry, but then you wouldn't be able to start a new mission until the channel was gone (15 minutes), which is not ideal in the case where you typo'd you mission and just complete it and resubmit directly after.

It seems like we would need a new table where the only columns are `channelid | is_complete` this table would be updated inside _cleanup_completed_mission but the entry would not be deleted until after the channel was deleted. We could then query that table on startup to see if there are any channelids with is_complete: 1 (true) and queue up the channel deletion again and remove the entry from the new table.

thoughts?
